### ISSUE TITLE
Extra field email_address

### ISSUE THREAD

**Issue by notbrokenjemma** [Comcast/tlsrpt_processor#4]
```
					sys.stdout.write(contact_info + csv_separator)
					sys.stdout.write(email_address + csv_separator)
```

From my reading of the spec I believe there is only a single field here, which should be contact_info?

**Comment by abrotman** [comment]
Ah, yep.  I wonder if I was intending to use the 5321 From there, but clearly that's not going to work the way it is.  I'll comment it out for the moment.  Thanks!

**Comment by abrotman** [comment]
Just flat out removed it.  Closing ticket.  Thanks again!
